package tn.esprit;

import com.codename1.db.Database;
import com.codename1.io.FileSystemStorage;

import com.codename1.io.Util;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;


import com.codename1.util.EasyThread;
import java.util.ArrayList;

import tn.esprit.entite.Article;
import tn.esprit.entite.Utilisateur;

import tn.esprit.profil.LoginForm;
import tn.esprit.services.BlogService;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class Main {

    private Form current;
    private Resources theme;
    public boolean firstRun = true;
    public ArrayList<Article> oldList;
    private static Utilisateur loggedUser;
    Database db;
    public void init(Object context) {
        // use two network threads instead of one
        //updateNetworkThreadCount(2);
        theme = UIManager.initFirstTheme("/theme");
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);
        Toolbar.setCenteredDefault(false);
           String path = Display.getInstance().getDatabasePath("MyDB.db");
        if(path != null && !FileSystemStorage.getInstance().exists(path)) {
            copyDb(path);
        }
    }
     private void copyDb(String path) {
        try(InputStream i = Display.getInstance().getResourceAsStream(getClass(), "/MyDB.db");
                OutputStream o = FileSystemStorage.getInstance().openOutputStream(path)) {
            Util.copy(i, o);
        } catch(IOException err) {
            System.out.println(err.getCause());
        }
    }
    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        
        try {
            db = Display.getInstance().openOrCreate("MyDB.db");
        } catch (IOException ex) {
            System.out.println(ex.getCause());
        }
        BlogService bS = new BlogService();
        Display.getInstance().callSerially(new Runnable() {
            public void run() {
                while (true) {
                        System.out.println("Tik!");
                        if (firstRun) {
                            System.out.println("First run");
                            oldList = bS.findAll();
                            
                            firstRun = false;
                        } else {
                            System.out.println("Not first run!" + bS.findAll().size() + " " + oldList.size());
                            if (oldList.size() < bS.findAll().size()) {
                                int diff = Math.abs(oldList.size() - bS.findAll().size());
                                Dialog.show("Notification", "Il y'a " + diff + " article" + (diff > 1 ? "s" : "") +
                                        ", consulter le blog!", "Hide", null);
                                oldList = bS.findAll();
                            }
                        }
                   
                }
            }
        });
        LoginForm lg=new LoginForm(theme);
        lg.setDb(db);
        lg.show();
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
